### PR TITLE
Add linkProps

### PR DESCRIPTION
**Pull request by caiolopes**
It also fix README id to id_str example

### CODE REVIEW

**Comment by mannynotfound** [comment]
Hmm. I think this prop is a little unclear. Nothing really lets you know that this is going to make the action link in the footer open as a new tab unless you follow the code.

Possible idea: add a `linkProps` that can take an object and assign it to all the links so you could do

`linkProps={{target: '_blank', rel: 'noreferrer'}}`

and have that propagate through to all links inside `react-tweet`

**Comment by caiolopes** [comment]
@mannynotfound oh, I realize that, so I change to your suggestion, and it really looks better because now it changes all links in the Tweet component to the desired behaviour.

**Comment by mannynotfound** [comment]
this LGTM! We should add a bit about this in the README. Thanks

**Comment by mannynotfound** [comment]
@caiolopes updated README and bumped these changes in `1.2.0`

**Pull request merged**
