### PR TITLE
Update for React 15.5.4

### PR DESCRIPTION
**Pull request by benkeen**
- Updates react, react-dom to 15.5.4
- Explicitly adds prop-types as separate dependency

### CODE REVIEW

**Comment by mannynotfound** [comment]
Hey! 

Thanks for this PR! I think you still have to change all the references at the bottom of the components from `React.PropTypes` to just `PropTypes` because its still throwing a deprecation warning. Otherwise this LGTM.

**Comment by benkeen** [comment]
Oops, thanks! Can't believe I missed that. I'll patch it up tonight and resubmit.

**Comment by benkeen** [comment]
@mannynotfound all fixed. Thanks for catching that :)

**Comment by MaxMillington** [comment]
+1

**Comment by mannynotfound** [comment]
version `1.1.1` should be good now, thanks again!

**Pull request merged**
